# Generated by Django 3.0.3 on 2020-02-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
